name: Update Translations

on:
  push:
    branches: [ main ]

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if en.json changed
        id: check
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^dictionaries/en\.json$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm install node-fetch@^3

      - name: Run translation update
        if: steps.check.outputs.changed == 'true'
        run: node scripts/update-translations.mjs

      - name: Commit changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dictionaries/
          if ! git diff --staged --quiet; then
            git commit -m "chore: auto-update translations based on en.json"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}